apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-templates
data:
  index-template: "<html>hello</html>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-hello-world
        image: gcr.io/GOOGLE_CLOUD_PROJECT/helloworld:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/templates
          name: flask-templates
        env:
        - name: PORT
          value: "8080"
      volumes:
        - name: flask-templates
          configMap:
            name: flask-templates
            items:
            - key: index-template
              path: index.html   
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8080
  type: ClusterIP
  selector:
    app: flask